"""
    scripts/paper/build_section.jl

Assemble the publication-ready results section. Inputs: paper/section_source.tex
(canonical prose with \\pv{key} references), paper/values.tex (generated by
scripts/paper/stats.jl), and the figures in paper/figs/ (generated by
scripts/paper/figures.jl). Output: paper/results_section.tex, a flattened,
\\input-ready fragment with literal numbers.

The build fails loudly on: a \\pv reference with no definition, a definition never
referenced, or a missing figure file. It then compiles the fragment once inside a
throwaway wrapper as a smoke test.

Usage: julia scripts/paper/build_section.jl
"""

using Dates

const PAPER = normpath(joinpath(@__DIR__, "..", "..", "paper"))
const SRC = joinpath(PAPER, "section_source.tex")
const VALS = joinpath(PAPER, "values.tex")
const OUT = joinpath(PAPER, "results_section.tex")
const SWEEP = "2026-06-07_f424438"

fail(msg) = (println("BUILD FAILED: ", msg); exit(1))

isfile(SRC) || fail("missing $SRC")
isfile(VALS) || fail("missing $VALS (run scripts/paper/stats.jl first)")

# parse definitions
defs = Dict{String,String}()
order = String[]
for line in eachline(VALS)
    m = match(r"^\\pvDefine\{([^}]+)\}\{(.*)\}\s*$", line)
    isnothing(m) && continue
    haskey(defs, m[1]) && fail("duplicate definition of pv key '$(m[1])'")
    defs[m[1]] = m[2]
    push!(order, m[1])
end
isempty(defs) && fail("no \\pvDefine entries found in values.tex")

# read source, dropping full-line comments (source-file commentary, not content)
src = join([l for l in eachline(SRC) if !startswith(lstrip(l), "%")], "\n")

# cross-check references vs definitions
refs = Set(m[1] for m in eachmatch(r"\\pv\{([^}]+)\}", src))
undef = sort(collect(setdiff(refs, keys(defs))))
unused = sort(collect(setdiff(keys(defs), refs)))
isempty(undef) || fail("undefined \\pv references: " * join(undef, ", "))
isempty(unused) || fail("unused values.tex definitions: " * join(unused, ", "))

# figure files must exist
figs = [m[1] for m in eachmatch(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", src)]
for f in figs
    isfile(joinpath(PAPER, f)) || fail("missing figure file: $f")
end

# flatten ("\pv{" is 4 characters, so the key is m[5:end-1])
flat = replace(src, r"\\pv\{([^}]+)\}" => m -> defs[m[5:end-1]])
occursin("\\pv{", flat) && fail("unflattened \\pv reference remains")

gitrev = try
    readchomp(`git -C $(normpath(joinpath(@__DIR__, "..", ".."))) rev-parse --short HEAD`)
catch
    "unknown"
end
header = """
% results_section.tex: GENERATED, do not edit.
% Built by scripts/paper/build_section.jl on $(Dates.format(now(), "yyyy-mm-dd HH:MM"))
% from section_source.tex + values.tex; sweep $SWEEP; repo commit $gitrev.
% Every number was computed from the saved sweep data by scripts/paper/stats.jl.
"""
write(OUT, header * flat * "\n")
println("wrote $OUT ($(length(refs)) values inlined, $(length(figs)) figures)")

# compile smoke test
build = joinpath(PAPER, "_build")
mkpath(build)
wrapper = joinpath(build, "wrapper.tex")
write(wrapper, """
\\documentclass[11pt]{article}
\\usepackage[letterpaper,margin=1in]{geometry}
\\usepackage{amsmath,amssymb,graphicx,booktabs}
\\usepackage[font=small,labelfont=bf]{caption}
\\graphicspath{{../}}
\\begin{document}
\\input{../results_section.tex}
\\end{document}
""")
ok = true
for pass in 1:2   # two passes for \\ref
    global ok
    p = run(pipeline(Cmd(`pdflatex -interaction=nonstopmode -halt-on-error wrapper.tex`; dir=build);
                     stdout=joinpath(build, "pdflatex.out"), stderr=joinpath(build, "pdflatex.out"));
            wait=true)
    ok &= success(p)
end
log = read(joinpath(build, "pdflatex.out"), String)
nerr = count("\n!", log)
pages = match(r"Output written on wrapper\.pdf \((\d+) page", log)
ok || fail("pdflatex failed; see paper/_build/pdflatex.out")
nerr == 0 || fail("$nerr LaTeX errors; see paper/_build/pdflatex.out")
println("compile check OK: $(isnothing(pages) ? "?" : pages[1]) pages, 0 errors (paper/_build/wrapper.pdf)")
