"""
    scripts/paper/build_section.jl

Assemble the publication-ready results section. Inputs: paper/section_source.tex
(canonical prose with \\pv{key} and \\pvcaption{name} references),
paper/captions.tex (hand-edited figure titles and captions),
paper/values.tex (data values, generated by scripts/paper/stats.jl),
paper/figmeta.tex (display conventions, generated by scripts/paper/figures.jl),
and the figures in paper/figs/. Output: paper/results_section.tex, a flattened,
\\input-ready fragment with literal numbers and captions inlined.

The build fails loudly on: a \\pv reference with no definition, a definition never
referenced, a \\pvcaption reference with no caption block, a caption block never
referenced, or a missing figure file. It then compiles the fragment inside a
throwaway wrapper as a smoke test.

Usage: julia scripts/paper/build_section.jl
"""

using Dates

const PAPER = normpath(joinpath(@__DIR__, "..", "..", "paper"))
const SRC = joinpath(PAPER, "section_source.tex")
const VALS = joinpath(PAPER, "values.tex")
const FIGMETA = joinpath(PAPER, "figmeta.tex")
const CAPS = joinpath(PAPER, "captions.tex")
const OUT = joinpath(PAPER, "results_section.tex")

fail(msg) = (println("BUILD FAILED: ", msg); exit(1))

isfile(SRC) || fail("missing $SRC")
isfile(VALS) || fail("missing $VALS (run scripts/paper/stats.jl first)")
isfile(FIGMETA) || fail("missing $FIGMETA (run scripts/paper/figures.jl first)")
isfile(CAPS) || fail("missing $CAPS (hand-edited caption source)")

# sweep id: taken from the header stats.jl writes into values.tex, so the
# provenance always names the data actually used
sweepm = match(r"% sweep: (\S+)", read(VALS, String))
SWEEP = isnothing(sweepm) ? "unknown" : sweepm[1]

# parse definitions: data values (values.tex) + display conventions (figmeta.tex)
defs = Dict{String,String}()
order = String[]
for vfile in (VALS, FIGMETA), line in eachline(vfile)
    m = match(r"^\\pvDefine\{([^}]+)\}\{(.*)\}\s*$", line)
    isnothing(m) && continue
    haskey(defs, m[1]) && fail("duplicate definition of pv key '$(m[1])' in $(basename(vfile))")
    defs[m[1]] = m[2]
    push!(order, m[1])
end
isempty(defs) && fail("no \\pvDefine entries found")

# parse titles and captions (hand-edited; one ptitle + one pcaption block per figure)
capsrc = read(CAPS, String)
caps = Dict{String,String}()
for m in eachmatch(r"\\begin\{pcaption\}\{(\w+)\}\s*(.*?)\s*\\end\{pcaption\}"s, capsrc)
    haskey(caps, m[1]) && fail("duplicate pcaption block '$(m[1])' in captions.tex")
    caps[m[1]] = m[2]
end
isempty(caps) && fail("no pcaption blocks found in captions.tex")
titles = Dict{String,String}()
for m in eachmatch(r"\\begin\{ptitle\}\{(\w+)\}\s*(.*?)\s*\\end\{ptitle\}"s, capsrc)
    haskey(titles, m[1]) && fail("duplicate ptitle block '$(m[1])' in captions.tex")
    titles[m[1]] = m[2]
end
isempty(titles) && fail("no ptitle blocks found in captions.tex")

# read source, dropping full-line comments (source-file commentary, not content)
src = join([l for l in eachline(SRC) if !startswith(lstrip(l), "%")], "\n")

# inject titles and captions, checking references both ways
for (cmd, defs_d, klen) in (("pvcaption", caps, 12), ("pvtitle", titles, 10))
    refs_c = Set(m[1] for m in eachmatch(Regex("\\\\$cmd\\{(\\w+)\\}"), src))
    undef_c = sort(collect(setdiff(refs_c, keys(defs_d))))
    unused_c = sort(collect(setdiff(keys(defs_d), refs_c)))
    isempty(undef_c) || fail("\\$cmd references with no block in captions.tex: " * join(undef_c, ", "))
    isempty(unused_c) || fail("captions.tex $cmd blocks never referenced: " * join(unused_c, ", "))
    global src = replace(src, Regex("\\\\$cmd\\{(\\w+)\\}") => m -> defs_d[m[klen:end-1]])
end

# cross-check references vs definitions
refs = Set(m[1] for m in eachmatch(r"\\pv\{([^}]+)\}", src))
undef = sort(collect(setdiff(refs, keys(defs))))
unused = sort(collect(setdiff(keys(defs), refs)))
isempty(undef) || fail("undefined \\pv references: " * join(undef, ", "))
isempty(unused) || fail("unused values.tex definitions: " * join(unused, ", "))

# figure files must exist
figs = [m[1] for m in eachmatch(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", src)]
for f in figs
    isfile(joinpath(PAPER, f)) || fail("missing figure file: $f")
end

# flatten ("\pv{" is 4 characters, so the key is m[5:end-1])
flat = replace(src, r"\\pv\{([^}]+)\}" => m -> defs[m[5:end-1]])
occursin("\\pv{", flat) && fail("unflattened \\pv reference remains")

gitrev = try
    readchomp(`git -C $(normpath(joinpath(@__DIR__, "..", ".."))) rev-parse --short HEAD`)
catch
    "unknown"
end
header = """
% results_section.tex: GENERATED, do not edit.
% Built by scripts/paper/build_section.jl on $(Dates.format(now(), "yyyy-mm-dd HH:MM"))
% from section_source.tex + captions.tex + values.tex + figmeta.tex;
% sweep $SWEEP; repo commit $gitrev.
% Every number was computed from the saved sweep data by scripts/paper/stats.jl.
"""
write(OUT, header * flat * "\n")
println("wrote $OUT ($(length(refs)) values inlined, $(length(figs)) figures)")

# compile smoke test
build = joinpath(PAPER, "_build")
mkpath(build)
wrapper = joinpath(build, "wrapper.tex")
write(wrapper, """
\\documentclass[11pt]{article}
\\usepackage[letterpaper,margin=1in]{geometry}
\\usepackage{amsmath,amssymb,graphicx,booktabs}
\\usepackage[font=small,labelfont=bf]{caption}
\\graphicspath{{../}}
% preview readability only (this wrapper is a smoke test, not the real paper):
% separate paragraphs by a blank line instead of an indent
\\setlength{\\parskip}{0.8\\baselineskip}
\\setlength{\\parindent}{0pt}
\\begin{document}
\\input{../results_section.tex}
\\end{document}
""")
ok = true
for pass in 1:2   # two passes for \\ref
    global ok
    p = run(pipeline(Cmd(`pdflatex -interaction=nonstopmode -halt-on-error wrapper.tex`; dir=build);
                     stdout=joinpath(build, "pdflatex.out"), stderr=joinpath(build, "pdflatex.out"));
            wait=true)
    ok &= success(p)
end
log = read(joinpath(build, "pdflatex.out"), String)
nerr = count("\n!", log)
pages = match(r"Output written on wrapper\.pdf \((\d+) page", log)
ok || fail("pdflatex failed; see paper/_build/pdflatex.out")
nerr == 0 || fail("$nerr LaTeX errors; see paper/_build/pdflatex.out")
println("compile check OK: $(isnothing(pages) ? "?" : pages[1]) pages, 0 errors (paper/_build/wrapper.pdf)")
