"""
    scripts/paper/build_supplement.jl

Compile the standalone Supplementary Material to paper/supplement.pdf. Inputs:
paper/supplement.tex (hand-edited standalone document), paper/supp_figmeta.tex
(display conventions, generated by scripts/paper/supp_figures.jl), and the
figures in paper/supp_figs/. This is the local entry point for rebuilding the
supplement; it shares nothing with build_section.jl, so the supplement and the
results section are built independently.

The build fails loudly on: a missing input, a \\pv reference in supplement.tex
with no matching \\pvDefine in supp_figmeta.tex, a generated definition never
referenced, or a missing figure file. It then compiles supplement.tex with
pdflatex (two passes, for the figure cross-references).

Run scripts/paper/supp_figures.jl first (it writes the figures and figmeta).

Usage: julia scripts/paper/build_supplement.jl
"""

using Dates

const PAPER = normpath(joinpath(@__DIR__, "..", "..", "paper"))
const SRC = joinpath(PAPER, "supplement.tex")
const FIGMETA = joinpath(PAPER, "supp_figmeta.tex")
const FIGDIR = joinpath(PAPER, "supp_figs")

fail(msg) = (println("BUILD FAILED: ", msg); exit(1))

isfile(SRC) || fail("missing $SRC")
isfile(FIGMETA) || fail("missing $FIGMETA (run scripts/paper/supp_figures.jl first)")

# generated display-convention definitions
defs = Set{String}()
for line in eachline(FIGMETA)
    m = match(r"^\\pvDefine\{([^}]+)\}\{.*\}\s*$", line)
    isnothing(m) || push!(defs, m[1])
end
isempty(defs) && fail("no \\pvDefine entries in $(basename(FIGMETA))")

# cross-check \pv references against the generated definitions. Scan only the
# document body (the preamble defines the \pv macro itself, e.g. \pv{#1}) with
# comment lines stripped, so neither the macro definition nor commentary counts.
src = read(SRC, String)
body = split(src, "\\begin{document}"; limit=2)[end]
body = join([l for l in split(body, '\n') if !startswith(lstrip(l), "%")], "\n")
refs = Set(m[1] for m in eachmatch(r"\\pv\{([^}]+)\}", body))
undef = sort(collect(setdiff(refs, defs)))
unused = sort(collect(setdiff(defs, refs)))
isempty(undef) || fail("\\pv references with no definition in supp_figmeta.tex: " * join(undef, ", "))
isempty(unused) || fail("supp_figmeta.tex definitions never referenced: " * join(unused, ", "))

# figure files must exist (paths are relative to \graphicspath{{supp_figs/}})
figs = [m[1] for m in eachmatch(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", src)]
for f in figs
    isfile(joinpath(FIGDIR, f)) || fail("missing figure file: supp_figs/$f")
end

# compile (two passes for figure cross-references), from the paper/ directory so
# \graphicspath{{supp_figs/}} and \input{supp_figmeta.tex} resolve
out = joinpath(PAPER, "supplement.pdflatex.out")
ok = true
for pass in 1:2
    global ok
    p = run(pipeline(Cmd(`pdflatex -interaction=nonstopmode -halt-on-error supplement.tex`; dir=PAPER);
                     stdout=out, stderr=out); wait=true)
    ok &= success(p)
end
log = read(out, String)
nerr = count("\n!", log)
pages = match(r"Output written on supplement\.pdf \((\d+) page", log)
ok || fail("pdflatex failed; see $(basename(out))")
nerr == 0 || fail("$nerr LaTeX errors; see $(basename(out))")
println("wrote paper/supplement.pdf ($(isnothing(pages) ? "?" : pages[1]) pages, ",
        "$(length(figs)) figures, 0 errors)")
