"""
    scripts/paper/build_section.jl

Assemble the publication-ready results section. Inputs: paper/section_source.tex
(canonical prose with \\pv{key} and \\pvcaption{name} references),
paper/captions.tex (hand-edited figure titles and captions),
output/main/values.tex (data values, generated by scripts/paper/stats.jl),
output/main/convergence/values.tex (generated by audit_convergence.jl),
output/main/figmeta.tex (display conventions, generated by scripts/paper/figures.jl),
output/ridge/paired/results/paper_values.tex (generated by ridge_supplement.jl),
output/ridge/ablations/results/paper_values.tex (generated by analyze_ablations.jl),
and the figures in output/main/figs/. Output: output/main/results_section.tex, a flattened,
\\input-ready fragment with literal numbers and captions inlined.

The build fails loudly on: a \\pv reference with no definition, a definition never
referenced, a \\pvcaption reference with no caption block, a caption block never
referenced, or a missing figure file. It then compiles the fragment inside a
throwaway wrapper as a smoke test.

Usage: julia scripts/paper/build_section.jl
"""

using Dates

include(joinpath(@__DIR__, "..", "reporting_provenance.jl"))

const PAPER = normpath(joinpath(@__DIR__, "..", "..", "paper"))
const GENERATED = normpath(joinpath(@__DIR__, "..", "..", "output", "main"))
const SRC = joinpath(PAPER, "section_source.tex")
const VALS = joinpath(GENERATED, "values.tex")
const CONVERGENCE_VALS = joinpath(GENERATED, "convergence", "values.tex")
const RIDGE_VALS = normpath(
    joinpath(GENERATED, "..", "ridge", "paired", "results", "paper_values.tex")
)
const ABLATION_VALS = normpath(
    joinpath(GENERATED, "..", "ridge", "ablations", "results", "paper_values.tex")
)
const FIGMETA = joinpath(GENERATED, "figmeta.tex")
const CAPS = joinpath(PAPER, "captions.tex")
const OUT = joinpath(GENERATED, "results_section.tex")
const REPORTING_PROVENANCE = reporting_git_provenance(
    normpath(joinpath(@__DIR__, "..", ".."))
)

fail(msg) = (println("BUILD FAILED: ", msg); exit(1))

isfile(SRC) || fail("missing $SRC")
isfile(VALS) || fail("missing $VALS (run scripts/paper/stats.jl first)")
isfile(CONVERGENCE_VALS) ||
    fail("missing $CONVERGENCE_VALS (run scripts/paper/audit_convergence.jl first)")
isfile(RIDGE_VALS) ||
    fail("missing $RIDGE_VALS (run scripts/paper/ridge_supplement.jl first)")
isfile(ABLATION_VALS) ||
    fail("missing $ABLATION_VALS (run scripts/ridge/analyze_ablations.jl first)")
isfile(FIGMETA) || fail("missing $FIGMETA (run scripts/paper/figures.jl first)")
isfile(CAPS) || fail("missing $CAPS (hand-edited caption source)")
provenance_files = (VALS, CONVERGENCE_VALS, RIDGE_VALS, ABLATION_VALS, FIGMETA)
analysis_commits = [
    validate_analysis_commit(
        REPORTING_PROVENANCE,
        recorded_analysis_commit(provenance_file);
        artifact=basename(provenance_file),
    ) for provenance_file in provenance_files
]
length(unique(analysis_commits)) == 1 || fail(
    "reporting inputs record different analysis commits: " *
    join(unique(analysis_commits), ", "),
)
const ANALYSIS_COMMIT = only(unique(analysis_commits))

# sweep id: taken from the header stats.jl writes into values.tex, so the
# provenance always names the data actually used
valsrc = read(VALS, String)
sweepm = match(r"% sweep: (\S+)", valsrc)
SWEEP = isnothing(sweepm) ? "unknown" : sweepm[1]
fixturem = match(r"% fixture: (.+)", valsrc)
FIXTURE_NOTE = isnothing(fixturem) ? "" : "% Fixture status: $(fixturem[1]).\n"

# Parse definitions: reported values, convergence values, and display conventions.
defs = Dict{String,String}()
order = String[]
for vfile in (VALS, CONVERGENCE_VALS, RIDGE_VALS, ABLATION_VALS, FIGMETA),
    line in eachline(vfile)

    m = match(r"^\\pvDefine\{([^}]+)\}\{(.*)\}\s*$", line)
    isnothing(m) && continue
    haskey(defs, m[1]) &&
        fail("duplicate definition of pv key '$(m[1])' in $(basename(vfile))")
    defs[m[1]] = m[2]
    push!(order, m[1])
end
isempty(defs) && fail("no \\pvDefine entries found")

# parse titles and captions (hand-edited; one ptitle + one pcaption block per figure)
capsrc = read(CAPS, String)
caps = Dict{String,String}()
for m in eachmatch(r"\\begin\{pcaption\}\{(\w+)\}\s*(.*?)\s*\\end\{pcaption\}"s, capsrc)
    haskey(caps, m[1]) && fail("duplicate pcaption block '$(m[1])' in captions.tex")
    caps[m[1]] = m[2]
end
isempty(caps) && fail("no pcaption blocks found in captions.tex")
titles = Dict{String,String}()
for m in eachmatch(r"\\begin\{ptitle\}\{(\w+)\}\s*(.*?)\s*\\end\{ptitle\}"s, capsrc)
    haskey(titles, m[1]) && fail("duplicate ptitle block '$(m[1])' in captions.tex")
    titles[m[1]] = m[2]
end
isempty(titles) && fail("no ptitle blocks found in captions.tex")

# read source, dropping full-line comments (source-file commentary, not content)
src = join([l for l in eachline(SRC) if !startswith(lstrip(l), "%")], "\n")

# inject titles and captions, checking references both ways
for (cmd, defs_d, klen) in (("pvcaption", caps, 12), ("pvtitle", titles, 10))
    refs_c = Set(m[1] for m in eachmatch(Regex("\\\\$cmd\\{(\\w+)\\}"), src))
    undef_c = sort(collect(setdiff(refs_c, keys(defs_d))))
    unused_c = sort(collect(setdiff(keys(defs_d), refs_c)))
    isempty(undef_c) ||
        fail("\\$cmd references with no block in captions.tex: " * join(undef_c, ", "))
    isempty(unused_c) ||
        fail("captions.tex $cmd blocks never referenced: " * join(unused_c, ", "))
    global src = replace(
        src, Regex("\\\\$cmd\\{(\\w+)\\}") => m -> defs_d[m[klen:(end - 1)]]
    )
end

# cross-check references vs definitions
refs = Set(m[1] for m in eachmatch(r"\\pv\{([^}]+)\}", src))
undef = sort(collect(setdiff(refs, keys(defs))))
unused = sort(collect(setdiff(keys(defs), refs)))
isempty(undef) || fail("undefined \\pv references: " * join(undef, ", "))
isempty(unused) || fail("unused values.tex definitions: " * join(unused, ", "))

# figure files must exist
figs = [m[1] for m in eachmatch(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", src)]
for f in figs
    isfile(joinpath(GENERATED, f)) || fail("missing figure file: $f")
end

# flatten ("\pv{" is 4 characters, so the key is m[5:end-1])
flat = replace(src, r"\\pv\{([^}]+)\}" => m -> defs[m[5:(end - 1)]])
occursin("\\pv{", flat) && fail("unflattened \\pv reference remains")

header = """
% results_section.tex: GENERATED, do not edit.
% Built by scripts/paper/build_section.jl on $(Dates.format(now(), "yyyy-mm-dd HH:MM"))
% from section_source.tex + captions.tex + values.tex + convergence/values.tex +
% Ridge and ablation values + figmeta.tex;
% sweep $SWEEP; analysis commit $ANALYSIS_COMMIT;
% manuscript commit $(REPORTING_PROVENANCE.commit); clean manuscript sources.
$(FIXTURE_NOTE)% Every number was computed from the saved sweep data by the reporting scripts.
"""
mkpath(GENERATED)
write(OUT, header * flat * "\n")
println("wrote $OUT ($(length(refs)) values inlined, $(length(figs)) figures)")

# Compile smoke test in a temporary directory.
mktempdir() do build
    wrapper = joinpath(build, "wrapper.tex")
    write(
        wrapper,
        """
\\documentclass[11pt]{article}
\\usepackage[letterpaper,margin=1in]{geometry}
\\usepackage{amsmath,amssymb,graphicx,booktabs}
\\usepackage[font=small,labelfont=bf]{caption}
\\graphicspath{{$(GENERATED)/}}
% preview readability only (this wrapper is a smoke test, not the real paper):
% separate paragraphs by a blank line instead of an indent
\\setlength{\\parskip}{0.8\\baselineskip}
\\setlength{\\parindent}{0pt}
\\begin{document}
\\input{$OUT}
\\end{document}
""",
    )
    log_path = joinpath(build, "pdflatex.out")
    ok = true
    for _ in 1:2   # two passes for \\ref
        process = run(
            pipeline(
                ignorestatus(
                    Cmd(
                        `pdflatex -interaction=nonstopmode -halt-on-error wrapper.tex`;
                        dir=build,
                    ),
                );
                stdout=log_path,
                stderr=log_path,
            );
            wait=true,
        )
        ok &= success(process)
    end
    log = read(log_path, String)
    nerr = count("\n!", log)
    pages = match(r"Output written on wrapper\.pdf \((\d+) page", log)
    ok || fail("pdflatex compile check failed")
    nerr == 0 || fail("$nerr LaTeX errors in compile check")
    println("compile check OK: $(isnothing(pages) ? "?" : pages[1]) pages, 0 errors")
end
