"""
    scripts/paper/ridge_supplement.jl

Emit the small set of base Ridge values quoted in the paper. The input is
`output/ridge/paired/figdata.jld2`, extracted from the complete base Ridge sweep
by `scripts/paper/figdata.jl`.

Outputs:

  * `output/ridge/paired/results/paper_values.tex`

No raw sweep access is required. Every reported value is computed from the
retained seed-level figure data. The input and output paths can be overridden
with `BROKERAGE_ABM_RIDGE_FIGDATA_PATH` and
`BROKERAGE_ABM_RIDGE_PAPER_VALUES_PATH`.

Usage: julia --project --threads=auto scripts/paper/ridge_supplement.jl
"""

include(joinpath(@__DIR__, "..", "monte_carlo.jl"))
include(joinpath(@__DIR__, "..", "reporting_provenance.jl"))

using JLD2
using Printf: @sprintf
using Statistics: median

const REPO = normpath(joinpath(@__DIR__, "..", ".."))
const INPUT = get(
    ENV,
    "BROKERAGE_ABM_RIDGE_FIGDATA_PATH",
    joinpath(REPO, "output", "ridge", "paired", "figdata.jld2"),
)
const VALUES = get(
    ENV,
    "BROKERAGE_ABM_RIDGE_PAPER_VALUES_PATH",
    joinpath(REPO, "output", "ridge", "paired", "results", "paper_values.tex"),
)
const BASELINE_REL = "oat/rho=0.5"

const PROVENANCE = reporting_git_provenance(REPO)
isfile(INPUT) || error("missing base Ridge figure data: $INPUT")
const FD = JLD2.load(INPUT)["figdata"]
const META = FD["meta"]
const DATA_ANALYSIS_COMMIT = validate_analysis_commit(
    PROVENANCE,
    META["analysis_git_commit"];
    artifact="base Ridge figure data",
)
META["analysis_source_clean"] == true ||
    error("base Ridge figure data were extracted from dirty analysis sources")
META["learning_model"] == "ridge" || error("expected base Ridge figure data")

const REGIMES = FD["regime_cells"]
length(REGIMES) == 98 || error("expected 98 effective base Ridge realizations")
all(length(cell["seeds"]) == (cell["rel"] == BASELINE_REL ? 50 : 20) for cell in REGIMES) ||
    error("unexpected base Ridge seed plan")

rank_interval(cell) = monte_carlo_interval(cell["seed_values"]["rankgap"])

const REGIME_POINTS = sort(
    [
        let interval = rank_interval(cell)
            (
                rel=cell["rel"],
                mean=interval.mean,
                lower=interval.lower,
                upper=interval.upper,
            )
        end for cell in REGIMES
    ];
    by=point -> point.mean,
)
const BASELINE = only(point for point in REGIME_POINTS if point.rel == BASELINE_REL)
const RIDGE_MEDIAN = median(point.mean for point in REGIME_POINTS)
const POSITIVE_N = count(point -> point.mean > 0.0, REGIME_POINTS)

function write_values()
    mkpath(dirname(VALUES))
    open(VALUES, "w") do io
        println(io, "% Generated by scripts/paper/ridge_supplement.jl.")
        println(io, "% Data analysis commit: $DATA_ANALYSIS_COMMIT")
        println(io, "% Reporting commit: $(PROVENANCE.commit)")
        println(io, "% Reporting source clean: $(PROVENANCE.source_clean)")
        println(io, "% Ridge sweep: ", META["sweep"])
        println(io, "\\pvDefine{ridgeNConditions}{$(length(REGIME_POINTS))}")
        println(io, "\\pvDefine{ridgePositiveN}{$POSITIVE_N}")
        println(io, "\\pvDefine{ridgeBaselineGap}{", @sprintf("%.3f", BASELINE.mean), "}")
        println(io, "\\pvDefine{ridgeMedianGap}{", @sprintf("%.3f", RIDGE_MEDIAN), "}")
    end
    println("wrote $VALUES")
    return nothing
end

write_values()
